language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

env:
  - PRO_SPECIAL_BUILD='early-access-vector'

install:
  - java pro_wrapper.java version

script:
  - ./pro/bin/pro build perfer
